<?php
/**
 * Single family partial template
 *
 * @package UnderStrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;
?>

<article <?php post_class(); ?> id="post-<?php the_ID(); ?>">

	<header class="entry-header col-md-6 family-stats">

		<?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
		 <div class="row family">
		 	<?php
		 		if( have_rows('family') ):

				    // Loop through rows.
				    while( have_rows('family') ) : the_row();

				        // Load sub field value.
				        $name = get_sub_field('name');
				        $bio = get_sub_field('bio_details');
				        $img = get_sub_field('bio_picture');
				        //var_dump($img);
				        echo '<div class="col-md-4">';
				        echo '<img src="'. $img['sizes']['medium'] .'" class="parent person img-fluid" alt="The Perez family father generated by https://generated.photos/face/neutral-latino-adult-male-with-short-black-hair-and-brown-eyes--5e6887cc6d3b380006f1dc89.">';
				        echo '<h2 class="family-member-name">' . $name . '</h2>';
				        echo '<div class="family-bio">' . $bio . '</div>';
				        echo '</div>';
				        // Do something...

				    // End loop.
				    endwhile;

				// No value.
				else :
				    // Do something...
				endif;

		 	?>

		 </div>

	</header><!-- .entry-header -->



	<div class="container-fluid article">
        <div class="row">                
            <div class="row offset-md-6">
				<?php the_content(); ?>
			</div>	
		</div>			
	</div>
<footer class="entry-footer">

	<?php understrap_entry_footer(); ?>

</footer><!-- .entry-footer -->
	

